/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-06 at 14:25:27 UTC 
 * Modify at your own risk.
 */

package com.appspot.twitterlitesample.message.model;

/**
 * Model definition for MessageGetDTO.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the message. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessageGetDTO extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long creation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isMessageFromCurrentUser;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String messageKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private UserGetDTO sender;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String text;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreation() {
    return creation;
  }

  /**
   * @param creation creation or {@code null} for none
   */
  public MessageGetDTO setCreation(java.lang.Long creation) {
    this.creation = creation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsMessageFromCurrentUser() {
    return isMessageFromCurrentUser;
  }

  /**
   * @param isMessageFromCurrentUser isMessageFromCurrentUser or {@code null} for none
   */
  public MessageGetDTO setIsMessageFromCurrentUser(java.lang.Boolean isMessageFromCurrentUser) {
    this.isMessageFromCurrentUser = isMessageFromCurrentUser;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMessageKey() {
    return messageKey;
  }

  /**
   * @param messageKey messageKey or {@code null} for none
   */
  public MessageGetDTO setMessageKey(java.lang.String messageKey) {
    this.messageKey = messageKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public UserGetDTO getSender() {
    return sender;
  }

  /**
   * @param sender sender or {@code null} for none
   */
  public MessageGetDTO setSender(UserGetDTO sender) {
    this.sender = sender;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getText() {
    return text;
  }

  /**
   * @param text text or {@code null} for none
   */
  public MessageGetDTO setText(java.lang.String text) {
    this.text = text;
    return this;
  }

  @Override
  public MessageGetDTO set(String fieldName, Object value) {
    return (MessageGetDTO) super.set(fieldName, value);
  }

  @Override
  public MessageGetDTO clone() {
    return (MessageGetDTO) super.clone();
  }

}
