/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-06 at 14:25:27 UTC 
 * Modify at your own risk.
 */

package com.appspot.twitterlitesample.message.model;

/**
 * Model definition for UserGetDTO.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the message. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserGetDTO extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long creation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String firstName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isFollowedByCurrentUser;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lastName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String login;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userKey;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreation() {
    return creation;
  }

  /**
   * @param creation creation or {@code null} for none
   */
  public UserGetDTO setCreation(java.lang.Long creation) {
    this.creation = creation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public UserGetDTO setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFirstName() {
    return firstName;
  }

  /**
   * @param firstName firstName or {@code null} for none
   */
  public UserGetDTO setFirstName(java.lang.String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsFollowedByCurrentUser() {
    return isFollowedByCurrentUser;
  }

  /**
   * @param isFollowedByCurrentUser isFollowedByCurrentUser or {@code null} for none
   */
  public UserGetDTO setIsFollowedByCurrentUser(java.lang.Boolean isFollowedByCurrentUser) {
    this.isFollowedByCurrentUser = isFollowedByCurrentUser;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastName() {
    return lastName;
  }

  /**
   * @param lastName lastName or {@code null} for none
   */
  public UserGetDTO setLastName(java.lang.String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogin() {
    return login;
  }

  /**
   * @param login login or {@code null} for none
   */
  public UserGetDTO setLogin(java.lang.String login) {
    this.login = login;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserKey() {
    return userKey;
  }

  /**
   * @param userKey userKey or {@code null} for none
   */
  public UserGetDTO setUserKey(java.lang.String userKey) {
    this.userKey = userKey;
    return this;
  }

  @Override
  public UserGetDTO set(String fieldName, Object value) {
    return (UserGetDTO) super.set(fieldName, value);
  }

  @Override
  public UserGetDTO clone() {
    return (UserGetDTO) super.clone();
  }

}
